services:
  open-webui:
    container_name: "open-webui"
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "${HOST_PORT}:8080"
    volumes:
      - "${DATA_PATH}:/app/backend/data"
    restart: unless-stopped
    networks:
      - "${NETWORK_NAME}"

networks:
  ollama:
    external: true
    name: "${NETWORK_NAME}"
